/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions.$sessionId'
import { Route as ApiPublicAgentPairRouteImport } from './routes/api/public/agent/pair'
import { Route as ApiPublicAgentRemoteAgentRouteImport } from './routes/api/public/agent/remote-agent'
import { Route as ApiPublicAgentSyncRouteImport } from './routes/api/public/agent/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAgentPairRoute = ApiPublicAgentPairRouteImport.update({
  id: '/api/public/agent/pair',
  path: '/api/public/agent/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRemoteAgentRoute =
  ApiPublicAgentRemoteAgentRouteImport.update({
    id: '/api/public/agent/remote-agent',
    path: '/api/public/agent/remote-agent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentSyncRoute = ApiPublicAgentSyncRouteImport.update({
  id: '/api/public/agent/sync',
  path: '/api/public/agent/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/api/public/agent/pair': typeof ApiPublicAgentPairRoute
  '/api/public/agent/remote-agent': typeof ApiPublicAgentRemoteAgentRoute
  '/api/public/agent/sync': typeof ApiPublicAgentSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/api/public/agent/pair': typeof ApiPublicAgentPairRoute
  '/api/public/agent/remote-agent': typeof ApiPublicAgentRemoteAgentRoute
  '/api/public/agent/sync': typeof ApiPublicAgentSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/api/public/agent/pair': typeof ApiPublicAgentPairRoute
  '/api/public/agent/remote-agent': typeof ApiPublicAgentRemoteAgentRoute
  '/api/public/agent/sync': typeof ApiPublicAgentSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agents'
    | '/dashboard'
    | '/sessions/$sessionId'
    | '/api/public/agent/pair'
    | '/api/public/agent/remote-agent'
    | '/api/public/agent/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agents'
    | '/dashboard'
    | '/sessions/$sessionId'
    | '/api/public/agent/pair'
    | '/api/public/agent/remote-agent'
    | '/api/public/agent/sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agents'
    | '/_authenticated/dashboard'
    | '/_authenticated/sessions/$sessionId'
    | '/api/public/agent/pair'
    | '/api/public/agent/remote-agent'
    | '/api/public/agent/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAgentPairRoute: typeof ApiPublicAgentPairRoute
  ApiPublicAgentRemoteAgentRoute: typeof ApiPublicAgentRemoteAgentRoute
  ApiPublicAgentSyncRoute: typeof ApiPublicAgentSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agent/pair': {
      id: '/api/public/agent/pair'
      path: '/api/public/agent/pair'
      fullPath: '/api/public/agent/pair'
      preLoaderRoute: typeof ApiPublicAgentPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/remote-agent': {
      id: '/api/public/agent/remote-agent'
      path: '/api/public/agent/remote-agent'
      fullPath: '/api/public/agent/remote-agent'
      preLoaderRoute: typeof ApiPublicAgentRemoteAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/sync': {
      id: '/api/public/agent/sync'
      path: '/api/public/agent/sync'
      fullPath: '/api/public/agent/sync'
      preLoaderRoute: typeof ApiPublicAgentSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSessionsSessionIdRoute: AuthenticatedSessionsSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAgentPairRoute: ApiPublicAgentPairRoute,
  ApiPublicAgentRemoteAgentRoute: ApiPublicAgentRemoteAgentRoute,
  ApiPublicAgentSyncRoute: ApiPublicAgentSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
